<?php

namespace QuetzalStudio\Flip;

class Reason
{
    const INACTIVE_ACCOUNT = 'INACTIVE_ACCOUNT';

    const NOT_REGISTERED_ACCOUNT  = 'NOT_REGISTERED_ACCOUNT';

    const CANT_RECEIVE_TRANSFER = 'CANT_RECEIVE_TRANSFER';

    const INTERMITTENT_DISTURBANCE_ON_BENEFICIARY_BANK = 'INTERMITTENT_DISTURBANCE_ON_BENEFICIARY_BANK';

    const BENEFICIARY_ACCOUNT_NOT_VERIFIED = 'BENEFICIARY_ACCOUNT_NOT_VERIFIED';
}
